# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("AccessControl"); Pkg.test("AccessControl"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("AccessControl")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
